Fix `entryLocale` validation code
linuxdeploy/linuxdeploy-desktopfile pull request #6
Opened 2021-05-12 21:44 UTC by ids1024

2021-05-12 21:47 UTC, ids1024 commented
Previously, `linuxdeploy` raised an error if the desktop file contained a line with a `-` in the key and a locale, since the locale checking code didn't allow `-`, and was applied to `entryName`. This seems to have broken AppImage builds for [Popsicle](https://github.com/pop-os/popsicle/).

2021-05-12 22:05 UTC, ids1024 commented
Oh, I see @mmstick opened an issue for this.

This should fix https://github.com/linuxdeploy/linuxdeploy-desktopfile/issues/5.

2021-05-13 09:24 UTC, TheAssassin requested changes

2021-05-13 09:24 UTC, TheAssassin commented on src/desktopfilereader.cpp
> +                                            (c == '[') || (c == ']')
This permits the use of `[` characters inside the locale part. I think you should remove this line, and iterate over the inner part only.

2021-05-13 09:27 UTC, TheAssassin commented on src/desktopfilereader.cpp
> +                                            (c == '[') || (c == ']')
Actually, no, this is handled elsewhere already. However, I find it confusing to permit these here. I am going to update your branch to iterate only over the inner part of the string.

2021-05-13 09:31 UTC, TheAssassin commented
We need to add a test case to make sure this won't be ignored in the future.

2021-05-13 09:38 UTC, TheAssassin commented
Seems like the existing check is already pretty broken. We have a test that is failing already on a locale like `de_DE.UTF-8` (which, according to https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html, should be valid). I'll fix that as well.

2021-05-13 12:18 UTC, TheAssassin approved these changes

2021-05-13 12:24 UTC, merged